# PBIP Data Generation

In [1]:
# Change source dir to project root
%cd ..

/data/pere.carrillo/pbi

/home/pere.carrillo/micromamba/envs/pbi-finetune/lib/python3.10/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [2]:
import os
import pandas as pd
from pathlib import Path
from Bio import SeqIO

In [ ]:
BASE_DIR = Path("data/PBIP")

# DATASET = "pbip_test"
# DATASET = "pbip_train"
DATASET = "predphi_train"
# DATASET = "predphi_test"

BAC_FASTA_DIR = BASE_DIR / "bac_faa_2021"
PHAGE_FASTA_DIR = BASE_DIR / "phage_faa_2021"
INTERACTIONS_CSV = BASE_DIR / f"{DATASET}_dataset.csv"

In [4]:
OUT_DIR = BASE_DIR / f"perphect_format/{DATASET}"
os.makedirs(OUT_DIR, exist_ok=True)

In [5]:
interactions = pd.read_csv(INTERACTIONS_CSV)

interactions = interactions.rename(columns={
    "phage": "phage_id",
    "host": "bacterium_id",
    "label": "interaction_type"
})

interactions.head()

    phage_id  bacterium_id  interaction_type
0   KM236502      CP027541                 1
1  NC_031124      CP027541                 1
2  NC_005357  MTKC01000003                 0
3   MH651183      CP027541                 1
4   MH051257      CP020567                 0

In [6]:
bacteria_ids = set(interactions["bacterium_id"])
print("Unique bacteria in interactions:", len(bacteria_ids))

bact_records = []

for bac_id in bacteria_ids:
    fasta_path = BAC_FASTA_DIR / f"{bac_id}.fasta"

    if not fasta_path.exists():
        print(f"[WARNING] Missing bacterial FASTA: {bac_id}")
        continue

    # Read ALL sequences in the file (all contigs)
    seqs = [str(rec.seq) for rec in SeqIO.parse(str(fasta_path), "fasta")]

    if len(seqs) == 0:
        print(f"[WARNING] Empty FASTA: {bac_id}")
        continue

    # Concatenate all contigs into one sequence
    merged_seq = "".join(seqs)
    length = len(merged_seq)

    bact_records.append((bac_id, merged_seq, length))

bacteria_df = pd.DataFrame(
    bact_records,
    columns=["bacterium_id", "bacterium_sequence", "sequence_length"]
)

print(f"Total bacteria loaded: {len(bacteria_df)}")
bacteria_df.head()

Unique bacteria in interactions: 194
[WARNING] Missing bacterial FASTA: CP020358
[WARNING] Missing bacterial FASTA: LR134359
[WARNING] Missing bacterial FASTA: CP027541
[WARNING] Missing bacterial FASTA: NZ_CDQJ01000001
[WARNING] Missing bacterial FASTA: CP035765
[WARNING] Missing bacterial FASTA: CP017065
[WARNING] Missing bacterial FASTA: QOUU01000001
[WARNING] Missing bacterial FASTA: NZ_OCQN01000001
[WARNING] Missing bacterial FASTA: RKJP01000005
[WARNING] Missing bacterial FASTA: NZ_KV917376
[WARNING] Missing bacterial FASTA: NZ_JNIU01000001
[WARNING] Missing bacterial FASTA: CP020369
[WARNING] Missing bacterial FASTA: CP029760
[WARNING] Missing bacterial FASTA: CP024679
[WARNING] Missing bacterial FASTA: CP025095
[WARNING] Missing bacterial FASTA: CP023483
[WARNING] Missing bacterial FASTA: LR134303
[WARNING] Missing bacterial FASTA: MH400164
[WARNING] Missing bacterial FASTA: NZ_AEUT02000001
[WARNING] Missing bacterial FASTA: NZ_LT629770
[WARNING] Missing bacterial FASTA: NZ_FNOF01000001
[WARNING] Missing bacterial FASTA: RKIY01000003
[WARNING] Missing bacterial FASTA: NZ_KN046823
[WARNING] Missing bacterial FASTA: QUAI01000001
[WARNING] Missing bacterial FASTA: CP025430
[WARNING] Missing bacterial FASTA: NZ_FOTC01000001
[WARNING] Missing bacterial FASTA: NZ_LR215978
[WARNING] Missing bacterial FASTA: QMJJ01000001
[WARNING] Missing bacterial FASTA: NZ_DF968533
[WARNING] Missing bacterial FASTA: CP022580
[WARNING] Missing bacterial FASTA: NZ_LT629758
[WARNING] Missing bacterial FASTA: NZ_CM001149
[WARNING] Missing bacterial FASTA: CP022426
[WARNING] Missing bacterial FASTA: SDYW01000001
[WARNING] Missing bacterial FASTA: CP014567
[WARNING] Missing bacterial FASTA: NZ_NGMG01000001
[WARNING] Missing bacterial FASTA: CP012831
[WARNING] Missing bacterial FASTA: NZ_UHDY01000002
[WARNING] Missing bacterial FASTA: NZ_GL622183
[WARNING] Missing bacterial FASTA: NZ_AGBZ02000001
[WARNING] Missing bacterial FASTA: NC_010163
[WARNING] Missing bacterial FASTA: CP032788
[WARNING] Missing bacterial FASTA: CP026100
[WARNING] Missing bacterial FASTA: CP034433
[WARNING] Missing bacterial FASTA: CP030279
[WARNING] Missing bacterial FASTA: CP011102
[WARNING] Missing bacterial FASTA: NZ_NQJM01000001
[WARNING] Missing bacterial FASTA: PEKX01000007
[WARNING] Missing bacterial FASTA: NZ_CP023484
[WARNING] Missing bacterial FASTA: CP030026
[WARNING] Missing bacterial FASTA: CP017605
[WARNING] Missing bacterial FASTA: NZ_UHFO01000001
[WARNING] Missing bacterial FASTA: NC_000001
[WARNING] Missing bacterial FASTA: CP014038
[WARNING] Missing bacterial FASTA: CP023315
[WARNING] Missing bacterial FASTA: CP020809
[WARNING] Missing bacterial FASTA: NZ_LT571449
[WARNING] Missing bacterial FASTA: PDLE01000004
[WARNING] Missing bacterial FASTA: CP005486
[WARNING] Missing bacterial FASTA: NZ_LK391965
[WARNING] Missing bacterial FASTA: NZ_UFTK01000001
[WARNING] Missing bacterial FASTA: NZ_CP023560
[WARNING] Missing bacterial FASTA: CP028813
[WARNING] Missing bacterial FASTA: CP014201
[WARNING] Missing bacterial FASTA: NZ_FLYG01000003
[WARNING] Missing bacterial FASTA: CP032627
[WARNING] Missing bacterial FASTA: KY464958
[WARNING] Missing bacterial FASTA: CP020451
[WARNING] Missing bacterial FASTA: NZ_UFTQ01000001
[WARNING] Missing bacterial FASTA: CP020557
[WARNING] Missing bacterial FASTA: CP031422
[WARNING] Missing bacterial FASTA: NZ_LT629739
[WARNING] Missing bacterial FASTA: NJFC02000001
[WARNING] Missing bacterial FASTA: LC361338
[WARNING] Missing bacterial FASTA: NZ_LFTY01000002
[WARNING] Missing bacterial FASTA: AP017936
[WARNING] Missing bacterial FASTA: NZ_ADEZ01000001
[WARNING] Missing bacterial FASTA: NZ_ATTH01000001
[WARNING] Missing bacterial FASTA: CP029449
[WARNING] Missing bacterial FASTA: MTKC01000003
[WARNING] Missing bacterial FASTA: NZ_LT897825
[WARNING] Missing bacterial FASTA: NZ_HF571038
[WARNING] Missing bacterial FASTA: AP014565
[WARNING] Missing bacterial FASTA: CP022298
[WARNING] Missing bacterial FASTA: CP023044
[WARNING] Missing bacterial FASTA: CP022674
[WARNING] Missing bacterial FASTA: NZ_MDHL01000001
[WARNING] Missing bacterial FASTA: NZ_CM002276
[WARNING] Missing bacterial FASTA: NZ_KE356190
[WARNING] Missing bacterial FASTA: NZ_AOLR01000018
[WARNING] Missing bacterial FASTA: MH841968
[WARNING] Missing bacterial FASTA: NZ_SAUP01000001
[WARNING] Missing bacterial FASTA: CP025034
[WARNING] Missing bacterial FASTA: NZ_UWXU01000001
[WARNING] Missing bacterial FASTA: NZ_CM002803
[WARNING] Missing bacterial FASTA: CP032410
[WARNING] Missing bacterial FASTA: MH286069
[WARNING] Missing bacterial FASTA: NZ_AOJL01000060
[WARNING] Missing bacterial FASTA: NZ_JYNI01000003
[WARNING] Missing bacterial FASTA: CP026337
[WARNING] Missing bacterial FASTA: CP029897
[WARNING] Missing bacterial FASTA: NZ_UHFW01000006
[WARNING] Missing bacterial FASTA: CP018363
[WARNING] Missing bacterial FASTA: MTZF01000001
[WARNING] Missing bacterial FASTA: NZ_GL545251
[WARNING] Missing bacterial FASTA: NZ_KI421518
[WARNING] Missing bacterial FASTA: CP027029
[WARNING] Missing bacterial FASTA: CP032523
[WARNING] Missing bacterial FASTA: NBTS02000002
[WARNING] Missing bacterial FASTA: CP014324
[WARNING] Missing bacterial FASTA: NZ_CCKZ01000001
[WARNING] Missing bacterial FASTA: NVUC01000001
[WARNING] Missing bacterial FASTA: CP019668
[WARNING] Missing bacterial FASTA: SIMC01000001
[WARNING] Missing bacterial FASTA: CP014013
[WARNING] Missing bacterial FASTA: AP018216
[WARNING] Missing bacterial FASTA: CP027116
[WARNING] Missing bacterial FASTA: NZ_CP029289
[WARNING] Missing bacterial FASTA: NZ_ALPT02000001
[WARNING] Missing bacterial FASTA: NZ_KV917375
[WARNING] Missing bacterial FASTA: NZ_KN046795
[WARNING] Missing bacterial FASTA: CP021694
[WARNING] Missing bacterial FASTA: CP029620
[WARNING] Missing bacterial FASTA: CP024710
[WARNING] Missing bacterial FASTA: NZ_JYBP01000003
[WARNING] Missing bacterial FASTA: CP034692
[WARNING] Missing bacterial FASTA: NZ_KN150939
[WARNING] Missing bacterial FASTA: CP019576
[WARNING] Missing bacterial FASTA: CP023558
[WARNING] Missing bacterial FASTA: NZ_JXYE01000002
[WARNING] Missing bacterial FASTA: NZ_CP016896
[WARNING] Missing bacterial FASTA: CP021427
[WARNING] Missing bacterial FASTA: NZ_MIGA01000001
[WARNING] Missing bacterial FASTA: CP018657
[WARNING] Missing bacterial FASTA: LR134235
[WARNING] Missing bacterial FASTA: NC_011184
[WARNING] Missing bacterial FASTA: NZ_CM001153
[WARNING] Missing bacterial FASTA: QBMC01000001
[WARNING] Missing bacterial FASTA: NZ_GG657757
[WARNING] Missing bacterial FASTA: CP024902
[WARNING] Missing bacterial FASTA: CM000737
[WARNING] Missing bacterial FASTA: NZ_MSEI01000003
[WARNING] Missing bacterial FASTA: NZ_AEUD01000001
[WARNING] Missing bacterial FASTA: NZ_AOLH01000002
[WARNING] Missing bacterial FASTA: NZ_LT961733
[WARNING] Missing bacterial FASTA: CP011458
[WARNING] Missing bacterial FASTA: NC_014640
[WARNING] Missing bacterial FASTA: NZ_FODB01000001
[WARNING] Missing bacterial FASTA: CP028366
[WARNING] Missing bacterial FASTA: CP020567
[WARNING] Missing bacterial FASTA: NZ_PETF01000001
[WARNING] Missing bacterial FASTA: QLNP01000098
[WARNING] Missing bacterial FASTA: NZ_JNYC01000004
[WARNING] Missing bacterial FASTA: CP020928
[WARNING] Missing bacterial FASTA: NVTK01000009
[WARNING] Missing bacterial FASTA: NZ_BAFC01000022
[WARNING] Missing bacterial FASTA: CP019236
[WARNING] Missing bacterial FASTA: NZ_KN150799
[WARNING] Missing bacterial FASTA: NZ_FNRZ01000004
[WARNING] Missing bacterial FASTA: NZ_UGVK01000001
[WARNING] Missing bacterial FASTA: NZ_FOYN01000001
[WARNING] Missing bacterial FASTA: NVUT01000001
[WARNING] Missing bacterial FASTA: CP018032
[WARNING] Missing bacterial FASTA: NREQ02000002
[WARNING] Missing bacterial FASTA: NZ_FNSA01000003
[WARNING] Missing bacterial FASTA: POWA01000006
[WARNING] Missing bacterial FASTA: NZ_UGJA01000003
[WARNING] Missing bacterial FASTA: NZ_FNLM01000034
[WARNING] Missing bacterial FASTA: NZ_QTTZ01000001
[WARNING] Missing bacterial FASTA: CP023567
[WARNING] Missing bacterial FASTA: NZ_QEOC01000001
[WARNING] Missing bacterial FASTA: NBSQ01000002
[WARNING] Missing bacterial FASTA: CP014636
[WARNING] Missing bacterial FASTA: NC_002771
[WARNING] Missing bacterial FASTA: NZ_CM007353
[WARNING] Missing bacterial FASTA: CP006870
[WARNING] Missing bacterial FASTA: MH202953
[WARNING] Missing bacterial FASTA: NZ_QEKR01000001
[WARNING] Missing bacterial FASTA: CP019892
[WARNING] Missing bacterial FASTA: NZ_UZVX01000004
[WARNING] Missing bacterial FASTA: NZ_JMSZ01000016
[WARNING] Missing bacterial FASTA: NC_016776
[WARNING] Missing bacterial FASTA: CP031023
[WARNING] Missing bacterial FASTA: NZ_CM001889
[WARNING] Missing bacterial FASTA: CP033337
[WARNING] Missing bacterial FASTA: LS483339
[WARNING] Missing bacterial FASTA: NZ_BCTM01000001
[WARNING] Missing bacterial FASTA: CP013922
[WARNING] Missing bacterial FASTA: NZ_CP018725
[WARNING] Missing bacterial FASTA: NZ_AOLS01000062
[WARNING] Missing bacterial FASTA: MF925712
[WARNING] Missing bacterial FASTA: NZ_CP029604
[WARNING] Missing bacterial FASTA: LT906480
[WARNING] Missing bacterial FASTA: RXKE01000007
Total bacteria loaded: 0

Empty DataFrame
Columns: [bacterium_id, bacterium_sequence, sequence_length]
Index: []

In [44]:
bacteria_df.to_csv(OUT_DIR/"bacteria_df.csv", index=False)

In [45]:
phage_records = []

phage_ids = set(interactions["phage_id"])
print(f"Unique phages in interactions: {len(phage_ids)}")

for ph_id in phage_ids:
    fasta_path = PHAGE_FASTA_DIR / f"{ph_id}.fasta"
    if not fasta_path.exists():
        print(f"[WARNING] Missing phage FASTA: {ph_id}")
        continue
    
    for rec in SeqIO.parse(str(fasta_path), "fasta"):
        seq = str(rec.seq)
        length = len(rec.seq)
        phage_records.append((ph_id, seq, length))

phages_df = pd.DataFrame(
    phage_records,
    columns=["phage_id", "phage_sequence", "sequence_length"]
)

print(f"Total phages loaded: {len(phages_df)}")
phages_df.head()

Unique phages in interactions: 83
Total phages loaded: 83

,phage_id,phage_sequence,sequence_length
0,PH-KP9074-1,ATTTTCCGAGGCTTACACGCAGGCGCGCCAGCTTTACGAGCAAATG...,48792
1,PH-KP8632,GGTGCGCAGAGCCGCGGTGGAAGAAAATGCGGCGAAATCCCCATAG...,58924
2,PHKP9471-A1,TAGCAGTGCCCCCCCCCCCCCTAAATTGACGCTAGGCACCCCCTAT...,41141
3,PH-KP9332_A1,CGCGAATGACGGTGAAGCGCCACTTGCCTAACCAGTGGAAGTAAAC...,49506
4,PH-KP9628-B1,TTCTCTTTCGCCGCCTGCTCTTTCGCGGCTTGTTCTTCCGCATCGA...,58597

In [46]:
phages_df.to_csv(OUT_DIR/"phages_df.csv", index=False)

In [47]:
interactions.to_csv(OUT_DIR/"couples_df.csv", index=False)